INSERT INTO colleges (
  name,
  slug,
  city,
  state,
  type,
  established_year,
  rating,
  acceptance_rate,
  annual_fees,
  average_package,
  highest_package,
  description,
  website,
  image_url,
  courses,
  facilities
) VALUES
(
  'North Valley Institute of Technology',
  'north-valley-institute-of-technology',
  'Pune',
  'Maharashtra',
  'Private',
  1998,
  4.5,
  21.5,
  185000,
  950000,
  3200000,
  'A technology-focused institute known for computer science, electronics, applied AI labs, and strong industry internships.',
  'https://example.edu/nvit',
  'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
  JSON_ARRAY('Computer Science', 'Electronics', 'Artificial Intelligence', 'Data Science'),
  JSON_ARRAY('Research Labs', 'Hostel', 'Sports Complex', 'Incubation Center')
),
(
  'Riverbend School of Business',
  'riverbend-school-of-business',
  'Bengaluru',
  'Karnataka',
  'Private',
  2007,
  4.3,
  32.0,
  245000,
  1200000,
  4100000,
  'A modern business school offering undergraduate management, analytics, and entrepreneurship programs with live consulting projects.',
  'https://example.edu/riverbend',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
  JSON_ARRAY('Business Administration', 'Finance', 'Marketing', 'Business Analytics'),
  JSON_ARRAY('Trading Lab', 'Library', 'Startup Studio', 'Auditorium')
),
(
  'Eastern State University',
  'eastern-state-university',
  'Kolkata',
  'West Bengal',
  'Public',
  1954,
  4.6,
  18.0,
  62000,
  760000,
  2800000,
  'A multidisciplinary public university with respected programs in sciences, humanities, economics, and public policy.',
  'https://example.edu/esu',
  'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
  JSON_ARRAY('Physics', 'Economics', 'Political Science', 'Mathematics'),
  JSON_ARRAY('Central Library', 'Hostel', 'Labs', 'Student Clubs')
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  city = VALUES(city),
  state = VALUES(state),
  type = VALUES(type),
  established_year = VALUES(established_year),
  rating = VALUES(rating),
  acceptance_rate = VALUES(acceptance_rate),
  annual_fees = VALUES(annual_fees),
  average_package = VALUES(average_package),
  highest_package = VALUES(highest_package),
  description = VALUES(description),
  website = VALUES(website),
  image_url = VALUES(image_url),
  courses = VALUES(courses),
  facilities = VALUES(facilities);
