INSERT INTO colleges (
  name,
  slug,
  city,
  state,
  type,
  established_year,
  rating,
  acceptance_rate,
  annual_fees,
  average_package,
  highest_package,
  description,
  website,
  image_url,
  courses,
  facilities
) VALUES
(
  'North Valley Institute of Technology',
  'north-valley-institute-of-technology',
  'Pune',
  'Maharashtra',
  'Private',
  1998,
  4.5,
  21.5,
  185000,
  950000,
  3200000,
  'A technology-focused institute known for computer science, electronics, applied AI labs, and strong industry internships.',
  'https://example.edu/nvit',
  'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1200&q=80',
  ARRAY['Computer Science', 'Electronics', 'Artificial Intelligence', 'Data Science'],
  ARRAY['Research Labs', 'Hostel', 'Sports Complex', 'Incubation Center']
),
(
  'Riverbend School of Business',
  'riverbend-school-of-business',
  'Bengaluru',
  'Karnataka',
  'Private',
  2007,
  4.3,
  32.0,
  245000,
  1200000,
  4100000,
  'A modern business school offering undergraduate management, analytics, and entrepreneurship programs with live consulting projects.',
  'https://example.edu/riverbend',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80',
  ARRAY['Business Administration', 'Finance', 'Marketing', 'Business Analytics'],
  ARRAY['Trading Lab', 'Library', 'Startup Studio', 'Auditorium']
),
(
  'Eastern State University',
  'eastern-state-university',
  'Kolkata',
  'West Bengal',
  'Public',
  1954,
  4.6,
  18.0,
  62000,
  760000,
  2800000,
  'A multidisciplinary public university with respected programs in sciences, humanities, economics, and public policy.',
  'https://example.edu/esu',
  'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1200&q=80',
  ARRAY['Physics', 'Economics', 'Political Science', 'Mathematics'],
  ARRAY['Central Library', 'Hostel', 'Labs', 'Student Clubs']
),
(
  'Lakeview College of Design',
  'lakeview-college-of-design',
  'Ahmedabad',
  'Gujarat',
  'Private',
  2012,
  4.1,
  38.5,
  210000,
  680000,
  1800000,
  'A studio-led design college with programs across product, communication, interaction, and fashion design.',
  'https://example.edu/lakeview',
  'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=1200&q=80',
  ARRAY['Product Design', 'Communication Design', 'UX Design', 'Fashion Design'],
  ARRAY['Design Studios', 'Material Lab', 'Gallery', 'Maker Space']
),
(
  'Sierra Medical College',
  'sierra-medical-college',
  'Jaipur',
  'Rajasthan',
  'Public',
  1986,
  4.4,
  12.0,
  135000,
  820000,
  2200000,
  'A medical college attached to a large teaching hospital, offering clinical exposure from the early years of study.',
  'https://example.edu/sierra-medical',
  'https://images.unsplash.com/photo-1576765607924-40930e683c3d?auto=format&fit=crop&w=1200&q=80',
  ARRAY['MBBS', 'Nursing', 'Physiotherapy', 'Public Health'],
  ARRAY['Teaching Hospital', 'Simulation Lab', 'Hostel', 'Library']
)
ON CONFLICT (slug) DO NOTHING;
